### ISSUE TITLE
NuxtPress Tag, Categories, Taxonomies, etc

### ISSUE THREAD

**Issue by junerockwell** [nuxt/press#101]
I've read through the NuxtPress Documentation (https://nuxt.press/en/guide/#setup) and maybe I just didn't get it but is there a way to add tags, categories, and/or custom taxonomy to each `.md` file and be able to have a page show a list of tags/categories/custom taxonomy? Is there also a way to have URLS generated for the taxonomies? For example, `somewebsite.com/:tags` or `somewebsite.com/:tag/:md_identifier`?

**Comment by pimlie** [comment]
Please have a look at https://github.com/nuxt/content, that module might be more suited for what you are looking for. Also nuxt/press has been deprecated somewhat in the mean time by nuxt/content so I wouldnt advise to use it at this moment if you could also use nuxt/content :)
