### ISSUE TITLE
add i18n example with nuxt-i18n

### ISSUE THREAD

**Issue by galvez** [nuxt/press#34]

**Comment by sustained** [comment]
Are you working on this currently or are you okay with someone else doing it?

**Comment by galvez** [comment]
Hey @sustained the current release already has basic support (see `docs/nuxt.press.json`, we're already working on improving it :)

**Comment by sustained** [comment]
I meant do you have some WIP branch that adds the **examples** for i18n? Because if so there's not much point in me trying to add the examples also.

I'll check that out, thanks!

**Comment by galvez** [comment]
We're working on a new internal i18n library first. Once that's done there we'll add more examples! Thank you.
