### ISSUE TITLE
Refactor source process to class

### ISSUE THREAD

**Issue by vinicius73** [nuxt/press#63]
The `source` object isn't a class. Because this there are code repeated and disallow extend this resource by config file.

**Comment by pimlie** [comment]
Thanks, actually `source` is an object so it can be overridden by users in their nuxt.press.json.

Eg for docs you could do:
```js
// nuxt.press.json
{
  docs: {
    ...
    source: {
      title: () => 'Static Title'
    }
...

and then `Static Title` will always be used instead of the default logic of using the first h1. Its easier to do this with plain objects then classes

**Comment by vinicius73** [comment]
Thanks. I didn't find any reference in the documentation and source code, so I think this feature didn't exist.
