### ISSUE TITLE
Can't really eject theme

### ISSUE THREAD

**Issue by anthonygore** [nuxt/press#75]
I don't want to use the default theme so I ejected CSS. However, theme.css gets loaded no matter what, and since the class `blog` is added to the root element, the CSS in theme.css is being applied. Any way to stop this?

**Comment by galvez** [comment]
Hey @anthonygore I think you're looking for `naked`:

https://github.com/nuxt/press/search?q=naked&unscoped_q=naked

**Comment by anthonygore** [comment]
I thought I tried that, but clearly I didn't. Sorry for the noise.

**Comment by galvez** [comment]
No worries, I've been completed swamped at work but should have time soon to release a new beta version. Past six weeks have been pretty hectic. 

Glad you're giving it a shot!
