### ISSUE TITLE
Specifying a blog slug causes error during yarn run generate

### ISSUE THREAD

**Issue by mccare** [nuxt/press#76]
When running `yarn run generate` and specifying a slug in a blog entry, there will be an exception `Cannot find module...`

Details:

In firstentry.md:
```md
---
title: My Blog Title
date: June 20, 2019
slug: this-title
---

# Blog Entry's Title
```

If you run 
```
yarn run generate
```
it will produce:

```
Error: Cannot find module                                
      '/sandbox/dist/_press/sources/blog/this-title'           
      Require stack:                                           
      - /sandbox/node_modules/@nuxt/press/dist/nuxt-press.js
```

If you edit firstentry.md in the blog directory and remove the slug line, yarn generate will finish without error.

This is with 0.0.1-beta4, Example here:
https://codesandbox.io/s/nuxt-press-examples-rd99q

**Comment by Glutnix** [comment]
Confirmed. I tried removing the minus between the words, same issue.

**Comment by mccare** [comment]
outdated
