### ISSUE TITLE
Is nuxt/press still relevant with nuxt/content?

### ISSUE THREAD

**Issue by ManUtopiK** [nuxt/press#98]
I was wondering differences between both?
Is nuxt/press still relevant with the new [nuxt/content](https://content.nuxtjs.org/)?

**Comment by galvez** [comment]
There hasn't been an official announcement yet, but nuxt/content ended up filling the role of nuxt/press in the ecosystem.

We might reuse bits of it here and there but nuxt/press is no longer being maintained in its current form.

**Comment by ManUtopiK** [comment]
Ok thanks, it's good to know !
